version: "3"

services:
  code-server:
    build: ./src
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "$HOME/$GOSRC:/home/coder/project/go/src"
      - "$HOME/$SAVEDWORKSPACE:/home/coder/saved_workspaces"
      - "config:$USERDATADIR"
      - "./coder-ssh:/home/coder/.ssh"
      - "./coder-home-shared/.bashrc:/home/coder/.bashrc"
      - "./coder-home-shared/.bashrc:/home/coder/.profile"
    environment:
      PASSWORD: "123"
      USERDATADIR: "$USERDATADIR"
    networks:
      code_server_nw:
        aliases:
          - code_server_nw_ext

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: $PWD/config
      o: bind

networks:
  code_server_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.100.0/24
