version: "3"

services:
  code-server:
    build: ./src
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "$GOSRC:/home/coder/project/go/src"
      - "./config:$USERDATADIR"
    environment:
      PASSWORD: "123"
      USERDATADIR: "$USERDATADIR"
